import type { Apartment } from './types';

export const APARTMENTS_DATA: Apartment[] = [
  {
    id: 1,
    title: 'شقة فاخرة بإطلالة على المدينة',
    location: 'وسط المدينة، دبي',
    price: 5000,
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    imageUrl: 'https://picsum.photos/seed/apt1/800/600',
    images: [
      'https://picsum.photos/seed/apt1-1/1200/800',
      'https://picsum.photos/seed/apt1-2/1200/800',
      'https://picsum.photos/seed/apt1-3/1200/800',
      'https://picsum.photos/seed/apt1-4/1200/800',
    ],
    description: 'شقة عصرية تقع في قلب المدينة النابض بالحياة، تتميز بتصميم داخلي أنيق وتشطيبات عالية الجودة. توفر إطلالات بانورامية خلابة على أفق المدينة من خلال نوافذها الكبيرة.',
    amenities: ['مسبح مشترك', 'صالة رياضية', 'موقف خاص', 'أمن 24/7', 'شرفة واسعة'],
    latitude: 25.1972,
    longitude: 55.2744,
  },
  {
    id: 2,
    title: 'استوديو أنيق بالقرب من الشاطئ',
    location: 'جميرا، دبي',
    price: 3500,
    bedrooms: 1,
    bathrooms: 1,
    area: 65,
    imageUrl: 'https://picsum.photos/seed/apt2/800/600',
    images: [
      'https://picsum.photos/seed/apt2-1/1200/800',
      'https://picsum.photos/seed/apt2-2/1200/800',
    ],
    description: 'استوديو مصمم بذوق رفيع على بعد خطوات من الشاطئ. مثالي للأفراد أو الأزواج الباحثين عن الهدوء والراحة. يحتوي على مطبخ مجهز بالكامل ومنطقة معيشة مريحة.',
    amenities: ['وصول مباشر للشاطئ', 'مطبخ مجهز', 'إنترنت فائق السرعة', 'تكييف مركزي'],
    latitude: 25.2225,
    longitude: 55.2695,
  },
  {
    id: 3,
    title: 'بنتهاوس مع تراس خاص',
    location: 'الخليج التجاري، دبي',
    price: 9500,
    bedrooms: 4,
    bathrooms: 5,
    area: 350,
    imageUrl: 'https://picsum.photos/seed/apt3/800/600',
    images: [
        'https://picsum.photos/seed/apt3-1/1200/800',
        'https://picsum.photos/seed/apt3-2/1200/800',
        'https://picsum.photos/seed/apt3-3/1200/800',
        'https://picsum.photos/seed/apt3-4/1200/800',
        'https://picsum.photos/seed/apt3-5/1200/800',
    ],
    description: 'بنتهاوس فخم يحتل الطابق العلوي من البرج، مع تراس خاص يوفر إطلالات 360 درجة على المدينة. يتميز بمساحات واسعة وتصميم فريد يجمع بين الفخامة والراحة.',
    amenities: ['تراس خاص', 'مسبح خاص', 'سينما منزلية', 'موقف لسيارتين', 'خدمة كونسيرج'],
    latitude: 25.1856,
    longitude: 55.2731,
  },
  {
    id: 4,
    title: 'شقة عائلية في مجمع سكني هادئ',
    location: 'المرابع العربية، دبي',
    price: 6000,
    bedrooms: 3,
    bathrooms: 3,
    area: 180,
    imageUrl: 'https://picsum.photos/seed/apt4/800/600',
    images: [
        'https://picsum.photos/seed/apt4-1/1200/800',
        'https://picsum.photos/seed/apt4-2/1200/800',
        'https://picsum.photos/seed/apt4-3/1200/800',
    ],
    description: 'شقة واسعة ومثالية للعائلات تقع ضمن مجمع سكني متكامل الخدمات يوفر بيئة آمنة وهادئة. بالقرب من المدارس والحدائق والمرافق الترفيهية.',
    amenities: ['حدائق ومناطق لعب', 'مدارس قريبة', 'نادي إجتماعي', 'مسارات للمشي'],
    latitude: 25.0489,
    longitude: 55.2214,
  },
  {
    id: 5,
    title: 'شقة حديثة في منطقة الأعمال',
    location: 'مركز دبي المالي العالمي',
    price: 4800,
    bedrooms: 1,
    bathrooms: 2,
    area: 90,
    imageUrl: 'https://picsum.photos/seed/apt5/800/600',
    images: [
        'https://picsum.photos/seed/apt5-1/1200/800',
        'https://picsum.photos/seed/apt5-2/1200/800',
    ],
    description: 'شقة بتصميم معاصر تناسب المحترفين والعاملين في منطقة الأعمال. توفر سهولة الوصول إلى الشركات والمطاعم والمقاهي الراقية.',
    amenities: ['صالة رياضية حديثة', 'قاعة اجتماعات', 'مقهى في المبنى', 'موقع استراتيجي'],
    latitude: 25.2124,
    longitude: 55.2818,
  },
  {
    id: 6,
    title: 'دوبلكس بإطلالة على المرسى',
    location: 'مرسى دبي',
    price: 8000,
    bedrooms: 3,
    bathrooms: 4,
    area: 250,
    imageUrl: 'https://picsum.photos/seed/apt6/800/600',
     images: [
        'https://picsum.photos/seed/apt6-1/1200/800',
        'https://picsum.photos/seed/apt6-2/1200/800',
        'https://picsum.photos/seed/apt6-3/1200/800',
    ],
    description: 'شقة دوبلكس فريدة من نوعها مع نوافذ تمتد من الأرض إلى السقف لتكشف عن إطلالات مائية ساحرة على مرسى دبي. تصميم داخلي فاخر ومساحات معيشة رحبة.',
    amenities: ['إطلالة على المرسى', 'طابقين', 'شرفة كبيرة', 'مسبح انفينيتي', 'ساونا وغرفة بخار'],
    latitude: 25.0770,
    longitude: 55.1384,
  },
];
